### ISSUE TITLE
Xamarin Demos TODO

### ISSUE THREAD

**Issue by MarcosCobena** [PlainConcepts/MobilityDay#1]
Ordered by priority:
- [ ] [WIP Marcos] Add iOS native project
- [ ] Add WP native Project
- [ ] Involve José Miguel so he can start with his session too
- [x] Real sessions data (everything local; JSON)
- [ ] Add our users (full name, description and pictures with base64; everything at JSON)
  - Pictures pending
- [x] Add Twitter URLs for the WebView (JSON)
- [ ] Minimal design to layouts (paddings, typefaces, etc.)
- [ ] Icons & splash screens (1 big size for each and scale down [icons] with https://www.syntaxismyui.com/imagemultiplier-add-in-for-xamarin-studio/)
